"""second-migration1

Revision ID: 313578c9ea55
Revises: 817de41942fc
Create Date: 2021-12-04 15:59:01.615530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313578c9ea55'
down_revision = '817de41942fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'disabled')
    # ### end Alembic commands ###
