"""second-migration1

Revision ID: 504fea536db3
Revises: f7b07283e00e
Create Date: 2021-12-03 00:13:59.075784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504fea536db3'
down_revision = 'f7b07283e00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'long_post')
    op.add_column('posts', sa.Column('long_post', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'long_post')
    op.add_column('comments', sa.Column('long_post', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
