"""second-migration1

Revision ID: c076ef3a0c0c
Revises: 504fea536db3
Create Date: 2021-12-03 00:17:50.968078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c076ef3a0c0c'
down_revision = '504fea536db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('long_post', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'long_post')
    # ### end Alembic commands ###
