"""second-migration1

Revision ID: f7b07283e00e
Revises: f73c803d6a73
Create Date: 2021-12-03 00:12:21.907979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b07283e00e'
down_revision = 'f73c803d6a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('long_post', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'long_post')
    # ### end Alembic commands ###
